### ISSUE TITLE
Delta download hangs due to an unhandled timeout error

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#432]
```
May 07 16:30:30 d72bc73 start-resin-supervisor[20115]: [2017-05-07T16:30:30.990Z] Event: Application delta download {"app":{"appId":"130151","commit":"xxxx","imageId":"registry2.resin.io/microbeastglobal/xxxxxxx","env":"{\"RESIN_APP_ID\":\"130151\",\"RESIN_APP_NAME\":\"microBeastGlobal\",\"RESIN_APP_RELEASE\":\"xxxxxxxx\",\"RESIN_DEVICE_UUID\":\"aaaaaaa\",\"RESIN_DEVICE_NAME_AT_INIT\":\"seattleD3\",\"RESIN_DEVICE_TYPE\":\"raspberrypi3\",\"RESIN_HOST_OS_VERSION\":\"Resin OS 2.0.0+rev2\",\"RESIN_SUPERVISOR_ADDRESS\":\"http://127.0.0.1:48484\",\"RESIN_SUPERVISOR_HOST\":\"127.0.0.1\",\"RESIN_SUPERVISOR_PORT\":48484,\"RESIN_SUPERVISOR_VERSION\":\"4.1.1\",\"RESIN\":\"1\",\"USER\":\"root\",\"ROTATE\":\"180\"}","config":"{\"RESIN_SUPERVISOR_DELTA\":\"1\"}","name":"microBeastGlobal"}}
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]: [2017-05-07T16:31:01.082Z] Unhandled rejection Error: ETIMEDOUT
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]:     at Timeout._onTimeout (/usr/src/app/node_modules/request/request.js:852:19)
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]:     at tryOnTimeout (timers.js:232:11)
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]:     at Timer.listOnTimeout (timers.js:202:5)
```

Seen on Resin OS 2.0.0+rev2 (prod) and Supervisor 4.1.1.

I'm still investigating where this happens, and why it's unhandled.

**Comment by pcarranzav** [comment]
A similar instance:
```
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]: [2017-05-07T17:06:47.605Z] Updating failed, but there is already another update scheduled immediately:  Error: 1 error: ESOCKETTIMEDOUT
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at /usr/src/app/src/application.js:1083:17
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:614:10)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:693:18)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:638:18)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at MappingPromiseArray.PromiseArray._resolve (/usr/src/app/node_modules/bluebird/js/release/promise_array.js:126:19)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at MappingPromiseArray._filter (/usr/src/app/node_modules/bluebird/js/release/map.js:127:10)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at MappingPromiseArray._promiseFulfilled (/usr/src/app/node_modules/bluebird/js/release/map.js:99:18)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at MappingPromiseArray.PromiseArray._iterate (/usr/src/app/node_modules/bluebird/js/release/promise_array.js:114:31)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at MappingPromiseArray.init (/usr/src/app/node_modules/bluebird/js/release/promise_array.js:78:10)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:566:21)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:614:10)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:693:18)
May 07 17:06:47 fa65fd0 start-resin-supervisor[4505]:     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:638:18)
May 07 17:06:48 fa65fd0 start-resin-supervisor[4505]: [2017-05-07T17:06:48.413Z] Event: Application delta download {"app":{"appId":"130151","commit":"00ba2a02968b96554eb501804dc8d6409035aa5d","imageId":"registry2.resin.io/microbeastglobal/00ba2a02968b96554eb501804dc8d6409035aa5d","env":"{\"RESIN_APP_ID\":\"130151\",\"RESIN_APP_NAME\":\"microBeastGlobal\",\"RESIN_APP_RELEASE\":\"00ba2a02968b96554eb501804dc8d6409035aa5d\",\"RESIN_DEVICE_UUID\":\"fa65fd0be09f5fc5e876650218960fef\",\"RESIN_DEVICE_NAME_AT_INIT\":\"seattleD6\",\"RESIN_DEVICE_TYPE\":\"raspberrypi3\",\"RESIN_HOST_OS_VERSION\":\"Resin OS 2.0.0+rev2\",\"RESIN_SUPERVISOR_ADDRESS\":\"http://127.0.0.1:48484\",\"RESIN_SUPERVISOR_HOST\":\"127.0.0.1\",\"RESIN_SUPERVISOR_PORT\":48484,\"RESIN_SUPERVISOR_VERSION\":\"4.1.1\",\"RESIN\":\"1\",\"USER\":\"root\",\"ROTATE\":\"0\"}","config":"{\"RESIN_SUPERVISOR_DELTA\":\"1\"}","name":"microBeastGlobal"}}
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]: [2017-05-07T17:07:18.569Z] Unhandled rejection Error: ESOCKETTIMEDOUT
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at ClientRequest.<anonymous> (/usr/src/app/node_modules/request/request.js:819:19)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at ClientRequest.g (events.js:286:16)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at emitNone (events.js:86:13)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at ClientRequest.emit (events.js:185:7)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at TLSSocket.emitTimeout (_http_client.js:614:10)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at TLSSocket.g (events.js:286:16)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at emitNone (events.js:86:13)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at TLSSocket.emit (events.js:185:7)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at TLSSocket.Socket._onTimeout (net.js:334:8)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at tryOnTimeout (timers.js:232:11)
May 07 17:07:18 fa65fd0 start-resin-supervisor[4505]:     at Timer.listOnTimeout (timers.js:202:5)
```

Weirdly it first timed out and was caught, and the next time it gave an unhandled exception.
