### ISSUE TITLE
Deleting a config.txt variable doesn't delete it from the file

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#450]
Logs show:
```
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]: [2017-06-09T21:40:35.283Z] Will not set boot config:  Error: Nothing to change
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at /usr/src/app/src/device.js:162:17
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Holder$3._callFunction (eval at generateHolderClass (/usr/src/app/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Holder$3.checkFulfillment (eval at generateHolderClass (/usr/src/app/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise.eval (eval at thenCallback (/usr/src/app/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:566:21)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:614:10)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:693:18)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:638:18)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at /usr/src/app/node_modules/bluebird/js/release/nodeback.js:42:21
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at tryToString (fs.js:455:3)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

[Forum](https://forums.resin.io/t/reset-config-variable-fleet-configuration-bug/1431/3)

**Comment by lekkas** [comment]
Hit this while setting up the Beast.

In summary, applying a specific dtoverlay fleet-wide (`RESIN_HOST_CONFIG_dtoverlay=pitft35-resistive,rotate=90,speed=25000000,fps=20`) rendered Pis with non-pitft35 screens non functional and required explicit removal of the offending `config.txt` setting (was done with a script because we have hundreds of Pis attached)

cc @pcarranzav @shaunmulligan @hedss since this affects Beast demos and can be a PITA in cases where the TFT screens are not homogeneous in a single app

**Comment by shaunmulligan** [comment]
@lekkas I believe the new Multicontainer supervisor now handles this case correctly as well as reflects the initial config.txt changes on first boot, so this should go away soon, but I agree its a PITA
