### ISSUE TITLE
Unable to determine if device has deviceApiKey support 

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-supervisor#475]
Supervisor version: 5.1.0
resinOS version: 2.0.8+rev1 

The supervisor isn't cleaning up app containers, there are 16 app containers running concurrently. I'm not sure if this is due to the following error (or the fact that the original container was preloaded). 
```
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]: [2017-07-24T16:18:19.161Z] Unable to determine if device has deviceApiKey support TypeError: Invalid Version: false
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at new SemVer (/usr/src/app/node_modules/semver/semver.js:279:11)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at compare (/usr/src/app/node_modules/semver/semver.js:566:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Function.gte (/usr/src/app/node_modules/semver/semver.js:615:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at hasDeviceApiKeySupport (/usr/src/app/src/bootstrap.js:247:54)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at /usr/src/app/src/bootstrap.js:262:24
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Promise._settlePromiseCtx (/usr/src/app/node_modules/bluebird/js/release/promise.js:606:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Async._drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:138:12)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:143:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Immediate.Async.drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at runCallback (timers.js:574:20)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at tryOnImmediate (timers.js:554:5)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at processImmediate [as _immediateCallback] (timers.js:533:5) TypeError: Invalid Version: false
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at new SemVer (/usr/src/app/node_modules/semver/semver.js:279:11)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at compare (/usr/src/app/node_modules/semver/semver.js:566:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Function.gte (/usr/src/app/node_modules/semver/semver.js:615:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at hasDeviceApiKeySupport (/usr/src/app/src/bootstrap.js:247:54)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at /usr/src/app/src/bootstrap.js:262:24
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:512:31)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:569:18)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Promise._settlePromiseCtx (/usr/src/app/node_modules/bluebird/js/release/promise.js:606:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Async._drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:138:12)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:143:10)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at Immediate.Async.drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at runCallback (timers.js:574:20)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at tryOnImmediate (timers.js:554:5)
Jul 24 16:18:19 01d9275 start-resin-supervisor[2264]:     at processImmediate [as _immediateCallback] (timers.js:533:5)
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_22cj)

**Comment by pcarranzav** [comment]
That error message shouldn't be related, and it was fixed in https://github.com/resin-io/resin-supervisor/pull/468

**Comment by pcarranzav** [comment]
Closing since the error message has to do with an issue that was already fixed, and the multiple containers have to do with other issues which are being dealt with in #482
