### ISSUE TITLE
The wrong device status can be reported when an update finishes

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-supervisor#485]
Seen on a specific user's app with supervisor v4.0.0 - some sort of race condition when there's bad network conditions causes an incorrect device status to be reported.
Device stays marked as "Stopping" or "Starting" when the correct status should be "Idle" ("Online" on the dashboard).
Logs show, right after the "Application started" event:
```
Aug 16 21:42:08 f8f2ebe start-resin-supervisor[5865]: [2017-08-16T21:42:08.766Z] Event: Device info update failure {"error":{"message":"ESOCKETTIMEDOUT","stack":"Error: ESOCKETTIMEDOUT\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/request/request.js:819:19)\n    at ClientRequest.g (events.js:286:16)\n    at emitNone (events.js:86:13)\n    at ClientRequest.emit (events.js:185:7)\n    at TLSSocket.emitTimeout (_http_client.js:614:10)\n    at TLSSocket.g (events.js:286:16)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket.Socket._onTimeout (net.js:334:8)\n    at tryOnTimeout (timers.js:232:11)\n    at Timer.listOnTimeout (timers.js:202:5)"},"stateDiff":{"status":"Starting"}}
```
And API logs show that a request did go through 7 seconds after that error was logged.
So the request must be going through, but some call to `device.updateState` must be failing or be overwritten. Needs investigation.

We don't know if the latest supervisor version is affected, but that part of the code doesn't seem to have changed since 4.0.0.

**Comment by pcarranzav** [comment]
It is highly probable that the cause for this was a device being moved between applications, and the Stop part being finished after the Start (since on a device move, they happened in parallel). In that case, this was fixed by https://github.com/resin-io/resin-supervisor/pull/499 - so I'm closing this, please reopen if it is seen again on a supervisor > 6.2.9.
