### ISSUE TITLE
[multicontainer] Issuing container "Stop" on a downloading service results in unhandled error

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-supervisor#578]
logs are as follows:
```
Mar 09 17:52:17 c2329be healthdog[1118]: [2018-03-09T17:52:17.088Z] Unhandled rejection Error: Can't set headers after they are sent.
Mar 09 17:52:17 c2329be healthdog[1118]:     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
Mar 09 17:52:17 c2329be healthdog[1118]:     at ServerResponse.j.set.j.header (/usr/src/app/dist/app.js:1:1559130)
Mar 09 17:52:17 c2329be healthdog[1118]:     at ServerResponse.j.send (/usr/src/app/dist/app.js:1:1555040)
Mar 09 17:52:17 c2329be healthdog[1118]:     at /usr/src/app/dist/app.js:1:1620453
Mar 09 17:52:17 c2329be healthdog[1118]:     at u (/usr/src/app/dist/app.js:1:75045)
Mar 09 17:52:17 c2329be healthdog[1118]:     at A._settlePromiseFromHandler (/usr/src/app/dist/app.js:1:773052)
Mar 09 17:52:17 c2329be healthdog[1118]:     at A._settlePromise (/usr/src/app/dist/app.js:1:773852)
Mar 09 17:52:17 c2329be healthdog[1118]:     at A._settlePromise0 (/usr/src/app/dist/app.js:1:774551)
Mar 09 17:52:17 c2329be healthdog[1118]:     at A._settlePromises (/usr/src/app/dist/app.js:1:775767)
Mar 09 17:52:17 c2329be healthdog[1118]:     at s._drainQueue (/usr/src/app/dist/app.js:1:778881)
Mar 09 17:52:17 c2329be healthdog[1118]:     at s._drainQueues (/usr/src/app/dist/app.js:1:778942)
Mar 09 17:52:17 c2329be healthdog[1118]:     at Immediate.drainQueues (/usr/src/app/dist/app.js:1:777153)
Mar 09 17:52:17 c2329be healthdog[1118]:     at runCallback (timers.js:574:20)
Mar 09 17:52:17 c2329be healthdog[1118]:     at tryOnImmediate (timers.js:554:5)
Mar 09 17:52:17 c2329be healthdog[1118]:     at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by pcarranzav** [comment]
Fixed in #579
