### ISSUE TITLE
Issue in docker-compose.yml service 'ports' entry parsing

### ISSUE THREAD

**Issue by Johnsel** [resin-io/resin-supervisor#618]
Hi guys,

First of all great work on the new microservices architecture, I'm very happy to work with it so far. I do seem to be having an issue where a seemingly valid entry in the docker-compose goes through the image building process but then blocks resin-supervisor from updating the application.

**Reproduction steps:**
1. Enter a "ports" entry in a docker-compose.yml service entry where the value is only a "port" value, not a "internalPort:externalPort", i.e. "1883" vs "1883:1883" (quotes for readability only) in the example below
2. Build the application as usual, which succeeds
3. After building, the application will not update on the clients. Resin-supervisor logs (balena logs xyz) shows the error further below.

**Workaround**
Use "expose" instead of "ports"

**Example:**
services:
 mqtt:
    build:
      context: images/mqtt
    ports:
      - 1883
    network_mode: host

**Supervisor error:**
[2018-04-04T17:35:35.594Z] Scheduling another update attempt due to failure: 30000 TypeError: x[c].match is not a function
at e.exports.e.getPortsAndPortBindings (/usr/src/app/dist/app.js:305:106570)
at e.getPortsAndPortBindings (/usr/src/app/dist/app.js:305:90939)
at new e (/usr/src/app/dist/app.js:305:98858)
at /usr/src/app/dist/app.js:545:72018
at u (/usr/src/app/dist/app.js:9:72709)
at A._settlePromiseFromHandler (/usr/src/app/dist/app.js:305:143588)
at A._settlePromise (/usr/src/app/dist/app.js:305:144388)
at A._settlePromise0 (/usr/src/app/dist/app.js:305:145087)
at A._settlePromises (/usr/src/app/dist/app.js:305:146414)
at s._drainQueue (/usr/src/app/dist/app.js:305:149417)
at s._drainQueues (/usr/src/app/dist/app.js:305:149478)
at Immediate.drainQueues (/usr/src/app/dist/app.js:305:147689)
at runCallback (timers.js:574:20)
at tryOnImmediate (timers.js:554:5)
at processImmediate [as _immediateCallback] (timers.js:533:5)
[2018-04-04T17:35:35.594Z] Apply error TypeError: x[c].match is not a function
[2018-04-04T17:36:05.595Z] Applying target state
[2018-04-04T17:36:05.651Z] Scheduling another update attempt due to failure: 30000 TypeError: x[c].match is not a function
at ..... and so on until

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_alxf)

**Comment by pcarranzav** [comment]
Hi @Johnsel! Thanks a lot for reporting this. We've tracked it down to a problem in how that ports entry is parsed in our backend before it's sent to the supervisor (single port entries are parsed as numbers instead of strings), and we've implemented a fix that should be reaching production soon. I'll note it here and close this issue when that happens.

**Comment by pcarranzav** [comment]
Hi @Johnsel - a fix has been deployed to our builder. I'll close this issue now, but please reopen if you still see the error message after pushing your code again.
