### ISSUE TITLE
Supervisor can occasionally die with event errors

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-supervisor#695]
The error shown is:
```
events.js:160
throw er; // Unhandled ‘error’ event
^
Error: write EPIPE
at exports._errnoException (util.js:1020:11)
at WriteWrap.afterWrite (net.js:812:14)
```

This seems to occur straight after initialisation, but it's hard to reproduce and more information is definitely needed.

**Comment by pdcastro** [comment]
That exact error and stack trace were observed on a device in this forum thread:
https://forums.balena.io/t/device-services-stuck-at-stopping-state/7131/

**Comment by nazrhom** [comment]
This appears to be related to https://github.com/knex/knex/issues/2143
The error is fixed in newer version of the library but is still present in some older ones. However newer versions introduce hard dependencies on the node version, leaving some users stuck with the bugged version
