### ISSUE TITLE
Failed to start service, network does not exists

### ISSUE THREAD

**Issue by imrehg** [resin-io/resin-supervisor#697]
Run into an issue where a service is not successfully started up. Multicontainer application:

```
Failed to start service 'main sha256:47160c00c49a9bd0326c87af343f7a16f261e4e0ff58c83d157e5b65c765c1dc' due to '(HTTP code 500) server error - failed to create endpoint main_362260_534817 on network 1026415_default: network 6dffaf763978d0421f5d858490ea357ee6b7615b2f245ca81e5ac714718d29aa does not exist '
```
The `main` service is using balena networking.
The logs are:
```
Jul 11 15:43:13 529d12f balenad[723]: [2018-07-11T15:43:13.757Z] Scheduling another update attempt due to failure:  30000 { Error: (HTTP code 500) server error - failed to create endpoint main_362260_534817 on network 1026415_default: network 6dffaf763978d0421f5d858490ea357ee6b7615b2f245ca81e5ac714718d29aa does not exist 
Jul 11 15:43:13 529d12f balenad[723]:     at /usr/src/app/dist/app.js:639:87497
Jul 11 15:43:13 529d12f balenad[723]:     at /usr/src/app/dist/app.js:639:87460
Jul 11 15:43:13 529d12f balenad[723]:     at m.buildPayload (/usr/src/app/dist/app.js:639:87470)
Jul 11 15:43:13 529d12f balenad[723]:     at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:639:86970)
Jul 11 15:43:13 529d12f balenad[723]:     at emitNone (events.js:91:20)
Jul 11 15:43:13 529d12f balenad[723]:     at IncomingMessage.emit (events.js:185:7)
Jul 11 15:43:13 529d12f balenad[723]:     at endReadableNT (_stream_readable.js:974:12)
Jul 11 15:43:13 529d12f balenad[723]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
Jul 11 15:43:13 529d12f balenad[723]:     at process._tickCallback (internal/process/next_tick.js:104:9)
Jul 11 15:43:13 529d12f balenad[723]:   reason: 'server error',
Jul 11 15:43:13 529d12f balenad[723]:   statusCode: 500,
Jul 11 15:43:13 529d12f balenad[723]:   json: { message: 'failed to create endpoint main_362260_534817 on network 1026415_default: network 6dffaf763978d0421f5d858490ea357ee6b7615b2f245ca81e5ac714718d29aa does not exist' } }
Jul 11 15:43:13 529d12f balenad[723]: [2018-07-11T15:43:13.763Z] Apply error Error: (HTTP code 500) server error - failed to create endpoint main_362260_534817 on network 1026415_default: network 6dffaf763978d0421f5d858490ea357ee6b7615b2f245ca81e5ac714718d29aa does not exist 
```
and the networks on the device:
```
root@529d12f:~# balena network ls
NETWORK ID          NAME                DRIVER              SCOPE
6dffaf763978        1026415_default     bridge              local
25793ad4154d        bridge              bridge              local
de9d9e4ea43c        host                host                local
2454af4c7d7c        none                null                local
48002325f839        supervisor0         bridge              local
```
It was on a resinOS 2.13.5 (custom build for some proxy testing).

There's another one when after a reboot:
```
23.05.18 08:33:07 (-0700) Failed to start service 'frontend sha256:a070b41682ba4aeae9796c38be9753df8086b9eae4dba000db7c75aac4662460' due to '(HTTP code 500) server error - failed to create endpointfrontend_290068_496734 on network 1099081_default: network 08148cdb13ad55101409c95e4b2121d354055d8a848e40291671497f39dc74e6 does not exist '
```

In both cases the device worked first, and hit this issue after reboot.

[Flowdock thread 1](https://www.flowdock.com/app/rulemotion/r-resinos/threads/JHiZB9PGg_peYyaY-hutdx5aMkK), [Flowdock thread 2](https://www.flowdock.com/app/rulemotion/r-supervisor/threads/LFgTWe22NxZa34ZwEKGquR1ZB2N).

**Comment by CameronDiver** [comment]
@memory I'm not sure this is the same issue, the supervisor would never try to create `docker0`. It's more likely that this is an issue in balenaEngine. That being said, I'm not going to rule out the supervisor having some role in causing this issue.

**Comment by memory** [comment]
Fair enough.  Paulo had suggested that this bug might be the one to append to; would you prefer I open a bug against balena-engine?

**Comment by CameronDiver** [comment]
I'd say leave it here for now, I'm still looking into how this could happen. It might be worth opening another issue in balena-engine and referencing this issues - thanks!
